import type { ExperienceSource } from '../models/experience.model';

export const EXPERIENCE_SOURCE: readonly ExperienceSource[] = [
  {
    id: 'techne',
    company: 'Techne',
    roleBR: 'Desenvolvedor Full Stack Pleno',
    roleEN: 'Mid-Level Full Stack Developer',
    periodBR: 'Jul 2024 — Presente',
    periodEN: 'Jul 2024 — Present',
    locationBR: 'São Paulo, Brasil',
    locationEN: 'São Paulo, Brazil',
    current: true,
    stacks: ['Angular', 'TypeScript', 'Java', 'Spring Boot', 'PostgreSQL', 'Temporal'],
    highlightsBR: [
      'Atuação em soluções de transformação digital para organizações públicas e privadas no Brasil.',
      'Desenvolvimento de sistemas nos segmentos de educação, gestão de pessoas, saúde e tecnologia.',
      'Foco em qualidade de entrega, boas práticas de engenharia e evolução contínua da stack.',
    ],
    highlightsEN: [
      'Building digital transformation solutions for public and private organizations across Brazil.',
      'Developing systems in education, human resources management, healthcare, and technology.',
      'Focused on delivery quality, engineering best practices, and continuous stack improvement.',
    ],
  },
  {
    id: 'vsm',
    company: 'VSM Informática',
    roleBR: 'Analista Programador Pleno II',
    roleEN: 'Mid-Level Programmer Analyst II',
    periodBR: 'Ago 2019 — Jul 2024',
    periodEN: 'Aug 2019 — Jul 2024',
    locationBR: 'Assis, São Paulo, Brasil',
    locationEN: 'Assis, São Paulo, Brazil',
    stacks: ['Java', 'Angular', 'TypeScript', 'Spring Boot', 'MySQL'],
    progression: [
      {
        roleBR: 'Analista Programador Pleno II',
        roleEN: 'Mid-Level Programmer Analyst II',
        periodBR: 'Out 2021 — Jul 2024',
        periodEN: 'Oct 2021 — Jul 2024',
      },
      {
        roleBR: 'Analista Programador Pleno I',
        roleEN: 'Mid-Level Programmer Analyst I',
        periodBR: 'Jul 2021 — Out 2021',
        periodEN: 'Jul 2021 — Oct 2021',
      },
      {
        roleBR: 'Analista Programador Júnior III',
        roleEN: 'Junior Programmer Analyst III',
        periodBR: 'Mar 2021 — Jul 2021',
        periodEN: 'Mar 2021 — Jul 2021',
      },
      {
        roleBR: 'Programador III',
        roleEN: 'Programmer III',
        periodBR: 'Out 2020 — Mar 2021',
        periodEN: 'Oct 2020 — Mar 2021',
      },
      {
        roleBR: 'Programador',
        roleEN: 'Programmer',
        periodBR: 'Ago 2019 — Out 2020',
        periodEN: 'Aug 2019 — Oct 2020',
      },
    ],
    highlightsBR: [
      'Quase 5 anos na VSM, com evolução consistente de Programador a Analista Programador Pleno II.',
      'Desenvolvimento de soluções completas de gestão para farmácias e drogarias em um único sistema.',
      'Participação contínua em projetos web com ênfase em escalabilidade e manutenibilidade.',
      'Reconhecido pelo empenho em aprender, incorporar feedback e elevar a qualidade técnica das entregas.',
    ],
    highlightsEN: [
      'Nearly 5 years at VSM, progressing consistently from Programmer to Mid-Level Programmer Analyst II.',
      'Built complete management solutions for pharmacies and drugstores in a unified platform.',
      'Ongoing work on web projects with a strong focus on scalability and maintainability.',
      'Recognized for learning drive, incorporating feedback, and raising the technical quality of deliveries.',
    ],
  },
  {
    id: 'fem-assis',
    company: 'Fundação Educacional do Município de Assis',
    roleBR: 'Desenvolvedor Web',
    roleEN: 'Web Developer',
    periodBR: 'Abr 2018 — Ago 2019',
    periodEN: 'Apr 2018 — Aug 2019',
    locationBR: 'Assis, São Paulo, Brasil',
    locationEN: 'Assis, São Paulo, Brazil',
    stacks: ['JavaScript', 'HTML', 'CSS', 'SQL'],
    highlightsBR: [
      'Desenvolvimento e manutenção de soluções web para o contexto educacional municipal.',
      'Implementação de interfaces e funcionalidades alinhadas às necessidades da instituição.',
      'Experiência prática construída em paralelo à graduação em Ciência da Computação.',
    ],
    highlightsEN: [
      'Developed and maintained web solutions for the municipal educational foundation.',
      'Implemented interfaces and features aligned with the institution’s operational needs.',
      'Hands-on experience built in parallel with a Computer Science bachelor’s degree.',
    ],
  },
];
